#!/usr/bin/env bash
set -euo pipefail
# Reads sentinel-patterns.json and emits a self-contained bash pre-push hook
# to stdout. The generated hook has zero runtime dependencies beyond bash,
# grep, and git.
#
# Usage: bash generate-hook.sh <path-to-sentinel-patterns.json> [HIVE_ROOT]
#        bash generate-hook.sh --print-marker
#
# When HIVE_ROOT is supplied, the generator also reads that Hive's
# `extensions.gates` directory and bakes any declared gate extensions into the
# emitted hook as an extra layer that runs AFTER the built-in pattern scan.
# Baking at generation time (rather than parsing YAML at push time) keeps the
# emitted hook free of runtime dependencies — the same approach already used
# for the patterns themselves.
#
# Gate extensions are ADDITIVE ONLY (design goal 3) and cannot suppress a
# built-in match (design goal 4): the pattern scan runs first and its failure
# is terminal, so no gate configuration can turn a dirty push clean.

# The marker that identifies a hook as ours. Operate mode Step 0 greps for this
# before regenerating, so a hand-hardened foreign hook is preserved rather than
# silently clobbered. Step 0 resolves it via `--print-marker` rather than
# hardcoding a second copy: if the two literals ever drifted, every real Apiary
# hook would be misclassified as foreign and freeze against pattern updates
# behind nothing louder than a warning.
SENTINEL_MARKER='Generated by Apiary Sentinel (generate-hook.sh) — do not hand-edit.'

# Dispatched before the arguments are validated — `--print-marker` takes none.
if [[ "${1:-}" == "--print-marker" ]]; then
  printf '%s\n' "$SENTINEL_MARKER"
  exit 0
fi

PATTERNS_JSON="${1:-}"
HIVE_ROOT_ARG="${2:-}"
if [[ -z "$PATTERNS_JSON" || ! -f "$PATTERNS_JSON" ]]; then
  echo "generate-hook.sh: usage: generate-hook.sh <sentinel-patterns.json> [HIVE_ROOT]" >&2
  echo "                 generate-hook.sh --print-marker" >&2
  exit 1
fi

# ---------------------------------------------------------------------------
# fm_field FILE KEY — echo the first frontmatter scalar value for KEY.
# Generation-time only; the emitted hook never parses YAML.
# ---------------------------------------------------------------------------
fm_field() {
  awk -v key="$2" '
    NR==1 && $0=="---" { infm=1; next }
    infm && $0=="---"  { exit }
    infm {
      if (index($0, key ":") == 1) {
        val = substr($0, length(key) + 2)
        sub(/^[ \t]+/, "", val); sub(/[ \t]+$/, "", val)
        # Strip inline comments, as gates_dir_from_hive_yml already does. Without
        # this, `timeout_seconds: 120 # note` fails the ^[0-9]+$ check and resets
        # to 0 (disabling the timeout), and a comment on `command:` comments out
        # the "$@" appended at invocation — so the gate silently inspects nothing.
        sub(/[[:space:]]*#.*$/, "", val)
        sub(/[[:space:]]+$/, "", val)
        gsub(/^["'"'"']|["'"'"']$/, "", val)
        print val; exit
      }
    }
  ' "$1" 2>/dev/null || true
}

# ---------------------------------------------------------------------------
# Resolve extensions.gates from hive.yml (nested one level under `extensions:`).
# ---------------------------------------------------------------------------
gates_dir_from_hive_yml() {
  local hive_yml="$1"
  [[ -f "$hive_yml" ]] || return 0
  awk '
    /^extensions:[[:space:]]*$/ { inext=1; next }
    inext && /^[^[:space:]#]/   { exit }
    inext && /^[[:space:]]+gates:[[:space:]]*/ {
      line=$0
      sub(/^[[:space:]]+gates:[[:space:]]*/, "", line)
      sub(/[[:space:]]*#.*$/, "", line)
      sub(/[[:space:]]+$/, "", line)
      gsub(/^["'"'"']|["'"'"']$/, "", line)
      if (line != "" && line != "null" && line != "~") print line
      exit
    }
  ' "$hive_yml" 2>/dev/null || true
}

# ---------------------------------------------------------------------------
# top_field_from_hive_yml FILE KEY — echo a top-level hive.yml scalar.
#   Generation-time only; the emitted hook never parses YAML. Used for
#   `default_branch`, which the hook needs to resolve a base commit when the
#   branch being pushed has no upstream yet.
# ---------------------------------------------------------------------------
top_field_from_hive_yml() {
  local hive_yml="$1"
  [[ -f "$hive_yml" ]] || return 0
  awk -v key="$2" '
    index($0, key ":") == 1 {
      line = substr($0, length(key) + 2)
      sub(/^[[:space:]]+/, "", line)
      sub(/[[:space:]]*#.*$/, "", line)
      sub(/[[:space:]]+$/, "", line)
      gsub(/^["'"'"']|["'"'"']$/, "", line)
      if (line != "" && line != "null" && line != "~") print line
      exit
    }
  ' "$hive_yml" 2>/dev/null || true
}

# ---------------------------------------------------------------------------
# class_from_hive_yml FILE — echo classification.max_level (nested one level
#   under `classification:`). Generation-time only, same approach as
#   gates_dir_from_hive_yml. Empty when the block is absent (= UNCLASSIFIED).
# ---------------------------------------------------------------------------
class_from_hive_yml() {
  local hive_yml="$1"
  [[ -f "$hive_yml" ]] || return 0
  awk '
    /^classification:[[:space:]]*$/ { incls=1; next }
    incls && /^[^[:space:]#]/       { exit }
    incls && /^[[:space:]]+max_level:[[:space:]]*/ {
      line=$0
      sub(/^[[:space:]]+max_level:[[:space:]]*/, "", line)
      sub(/[[:space:]]*#.*$/, "", line)
      sub(/[[:space:]]+$/, "", line)
      gsub(/^["'"'"']|["'"'"']$/, "", line)
      if (line != "" && line != "null" && line != "~") print line
      exit
    }
  ' "$hive_yml" 2>/dev/null || true
}

# ---------------------------------------------------------------------------
# Discover gate extensions: *.md files carrying `type: gate-extension`.
# Malformed entries are skipped with a warning rather than silently dropped.
#
# One tab-delimited record per gate rather than five parallel arrays: the fields
# can only ever be appended, emitted, and read back together, and a set of
# parallel arrays that drifted in length would be read positionally into empty
# strings rather than erroring. `required_tools` is deliberately last — it is
# the field most often empty, and `read` assigns a missing trailing field the
# empty string.
# ---------------------------------------------------------------------------
GATES=()

# The Hive's default branch, baked in so the emitted hook can resolve a base
# commit for a branch with no upstream. Empty when generated without a
# HIVE_ROOT; the hook then falls back to asking git.
DEFAULT_BRANCH=""
if [[ -n "$HIVE_ROOT_ARG" ]]; then
  DEFAULT_BRANCH="$(top_field_from_hive_yml "$HIVE_ROOT_ARG/hive.yml" default_branch)"
fi

# The Hive's classification ceiling, baked in (uppercased) so the emitted hook
# can run the banner scan without parsing YAML at push time. Empty (= treat as
# UNCLASSIFIED) when generated without a HIVE_ROOT or when hive.yml omits the
# classification block.
CLASS_MAX_LEVEL=""
if [[ -n "$HIVE_ROOT_ARG" ]]; then
  CLASS_MAX_LEVEL="$(class_from_hive_yml "$HIVE_ROOT_ARG/hive.yml" | tr '[:lower:]' '[:upper:]')"
fi

if [[ -n "$HIVE_ROOT_ARG" ]]; then
  gates_rel="$(gates_dir_from_hive_yml "$HIVE_ROOT_ARG/hive.yml")"
  if [[ -n "$gates_rel" ]]; then
    gates_abs="$HIVE_ROOT_ARG/${gates_rel#/}"
    if [[ -d "$gates_abs" ]]; then
      while IFS= read -r gf; do
        [[ -n "$gf" ]] || continue
        [[ "$(fm_field "$gf" type)" == "gate-extension" ]] || continue

        g_name="$(fm_field "$gf" gate)"
        g_cmd="$(fm_field "$gf" command)"
        g_onerr="$(fm_field "$gf" on_error)"
        g_timeout="$(fm_field "$gf" timeout_seconds)"
        g_tools="$(fm_field "$gf" required_tools)"

        if [[ -z "$g_name" || -z "$g_cmd" ]]; then
          echo "generate-hook.sh: skipping $gf — needs both 'gate' and 'command' in frontmatter" >&2
          continue
        fi
        # Fail closed by default: an unrunnable hardening layer blocks the push
        # rather than waving it through. A gate that degrades to "allow" is
        # worse than no gate once contributors trust it.
        [[ "$g_onerr" == "warn" ]] || g_onerr="block"
        [[ "$g_timeout" =~ ^[0-9]+$ ]] || g_timeout=0
        g_tools="${g_tools#[}"; g_tools="${g_tools%]}"; g_tools="${g_tools//,/ }"
        # Tab is the record separator, so it cannot survive inside a field.
        g_name="${g_name//$'\t'/ }"; g_cmd="${g_cmd//$'\t'/ }"
        g_tools="${g_tools//$'\t'/ }"

        GATES+=("$g_name"$'\t'"$g_cmd"$'\t'"$g_onerr"$'\t'"$g_timeout"$'\t'"$g_tools")
      done < <(find "$gates_abs" -maxdepth 1 -name '*.md' ! -name '_*' 2>/dev/null | sort)
    else
      echo "generate-hook.sh: extensions.gates points at '$gates_rel', not a directory under the Hive root; no gate extensions baked in." >&2
    fi
  fi
fi

PATTERN_COUNT=$(jq '.patterns | length' "$PATTERNS_JSON")

# Build arrays: names, regexes (ERE, no (?i)), icase flags
NAMES=()
REGEXES=()
ICASE=()

for ((i=0; i<PATTERN_COUNT; i++)); do
  name=$(jq -r ".patterns[$i].name" "$PATTERNS_JSON")
  regex=$(jq -r ".patterns[$i].regex" "$PATTERNS_JSON")

  icase=0
  if [[ "$regex" == '(?i)'* ]]; then
    icase=1
    regex="${regex#'(?i)'}"
  fi

  NAMES+=("$name")
  REGEXES+=("$regex")
  ICASE+=("$icase")
done

# Emit header. The marker line comes from $SENTINEL_MARKER rather than being
# spelled out in this heredoc, so `--print-marker` and the emitted hook cannot
# disagree. The heredoc stays quoted so nothing else here is interpolated.
cat <<'HEADER'
#!/usr/bin/env bash
set -euo pipefail
HEADER
printf '# %s\n' "$SENTINEL_MARKER"
cat <<'HEADER'
# Source of truth: assets/sentinel-patterns.json
# Regenerated on every operate-mode session (Step 0).

HEADER

# Emit pattern arrays — use printf %q for safe quoting
echo "# --- Embedded patterns (compiled from sentinel-patterns.json) ---"
printf 'PATTERN_NAMES=('
for name in "${NAMES[@]}"; do
  printf ' %q' "$name"
done
printf ' )\n'

printf 'PATTERN_REGEXES=('
for regex in "${REGEXES[@]}"; do
  printf ' %q' "$regex"
done
printf ' )\n'

printf 'PATTERN_ICASE=('
for flag in "${ICASE[@]}"; do
  printf ' %s' "$flag"
done
printf ' )\n'

printf 'PATTERN_COUNT=%d\n\n' "$PATTERN_COUNT"

# Emit baked-in gate extensions. When the Hive declares none this is an empty
# array and a zero count, and the hook's *behavior* is identical to the
# pre-extension output — the gate-running code below is emitted either way.
echo "# --- Baked-in gate extensions (compiled from extensions.gates) ---"
printf 'GATES=('
for g in "${GATES[@]+"${GATES[@]}"}"; do printf ' %q' "$g"; done
printf ' )\n'
printf 'GATE_COUNT=%d\n' "${#GATES[@]}"
printf 'DEFAULT_BRANCH=%q\n' "$DEFAULT_BRANCH"
printf 'CLASS_MAX_LEVEL=%q\n\n' "$CLASS_MAX_LEVEL"

# Emit the static body of the hook
cat <<'HOOK_BODY'
# ---------------------------------------------------------------------------
# split_frontmatter FILE
#   Sets BODY_LINES (array of body lines), BODY_START_LINE (1-based absolute
#   line number where body begins), FM_SCAN_LINES (frontmatter lines as
#   "ABS_LINENO<TAB>CONTENT" — scanned for credential/PII patterns too, since a
#   secret in a frontmatter scalar leaks exactly like one in the body), and
#   HAS_CLASSIFICATION_FM (1 if frontmatter carries a `classification:` field).
#   The `sentinel_override:` block is excluded from FM_SCAN_LINES so an
#   override's own recorded excerpts cannot re-trigger the scan.
# ---------------------------------------------------------------------------
split_frontmatter() {
  local file="$1"
  BODY_LINES=()
  BODY_START_LINE=1
  FM_SCAN_LINES=()
  HAS_CLASSIFICATION_FM=0

  local lineno=0
  local fm_start=0
  local fm_end=0
  local in_override=0

  while IFS= read -r line || [[ -n "$line" ]]; do
    ((lineno++)) || true
    if [[ $fm_start -eq 0 && $lineno -eq 1 && "$line" == "---" ]]; then
      fm_start=1
      continue
    fi
    if [[ $fm_start -eq 1 && $fm_end -eq 0 && "$line" == "---" ]]; then
      fm_end=1
      BODY_START_LINE=$((lineno + 1))
      continue
    fi
    if [[ $fm_start -eq 1 && $fm_end -eq 0 ]]; then
      if [[ $in_override -eq 0 && "$line" == "sentinel_override:"* ]]; then
        in_override=1
        continue
      fi
      if [[ $in_override -eq 1 ]]; then
        if [[ "$line" =~ ^[^[:space:]] ]]; then
          in_override=0
        else
          continue
        fi
      fi
      [[ "$line" == "classification:"* ]] && HAS_CLASSIFICATION_FM=1
      FM_SCAN_LINES+=("$(printf '%d\t%s' "$lineno" "$line")")
      continue
    fi
    if [[ $fm_end -eq 1 ]]; then
      BODY_LINES+=("$line")
    fi
  done < "$file"

  # No frontmatter found (or never closed) — entire file is body. Reset the
  # classification flag too: a malformed frontmatter block must not count as a
  # marking (fail closed, matching what the schema validator would say).
  if [[ $fm_end -eq 0 ]]; then
    BODY_LINES=()
    BODY_START_LINE=1
    FM_SCAN_LINES=()
    HAS_CLASSIFICATION_FM=0
    while IFS= read -r line || [[ -n "$line" ]]; do
      BODY_LINES+=("$line")
    done < "$file"
  fi
}

# ---------------------------------------------------------------------------
# parse_override FILE
#   Outputs overridden pattern names to stdout, one per line.
# ---------------------------------------------------------------------------
parse_override() {
  local file="$1"
  local in_fm=0
  local in_override=0
  local in_patterns=0
  local lineno=0

  while IFS= read -r line || [[ -n "$line" ]]; do
    ((lineno++)) || true
    if [[ $in_fm -eq 0 && $lineno -eq 1 && "$line" == "---" ]]; then
      in_fm=1; continue
    fi
    if [[ $in_fm -eq 1 && "$line" == "---" ]]; then
      break
    fi
    [[ $in_fm -eq 0 ]] && continue

    # Detect sentinel_override: block start
    if [[ $in_override -eq 0 && "$line" == "sentinel_override:"* ]]; then
      in_override=1; continue
    fi
    [[ $in_override -eq 0 ]] && continue

    # Non-indented line ends the block
    if [[ "$line" =~ ^[^[:space:]] ]]; then
      break
    fi

    local stripped="${line#"${line%%[![:space:]]*}"}"  # ltrim

    if [[ "$stripped" == "patterns:"* ]]; then
      in_patterns=1
      local rest="${stripped#patterns:}"
      rest="${rest#"${rest%%[![:space:]]*}"}"  # ltrim rest
      # Inline array: patterns: [a, b]
      if [[ "$rest" == "["*"]" ]]; then
        rest="${rest#[}"; rest="${rest%]}"
        IFS=',' read -ra items <<< "$rest"
        for item in "${items[@]}"; do
          item="${item#"${item%%[![:space:]]*}"}"; item="${item%"${item##*[![:space:]]}"}"
          item="${item#\"}"; item="${item%\"}"; item="${item#\'}"; item="${item%\'}"
          [[ -n "$item" ]] && printf '%s\n' "$item"
        done
        in_patterns=0
      fi
      continue
    fi

    if [[ $in_patterns -eq 1 ]]; then
      if [[ "$stripped" == "- "* ]]; then
        local val="${stripped#- }"
        val="${val#"${val%%[![:space:]]*}"}"; val="${val%"${val##*[![:space:]]}"}"
        val="${val#\"}"; val="${val%\"}"; val="${val#\'}"; val="${val%\'}"
        [[ -n "$val" && "$val" != *":"* ]] && printf '%s\n' "$val"
      elif [[ "$stripped" == *":"* ]]; then
        in_patterns=0
      fi
    fi
  done < "$file"
}

# ---------------------------------------------------------------------------
# parse_override_matches FILE
#   Outputs the excerpt strings recorded under sentinel_override.matches:,
#   one per line. When present, an override covers a pattern ONLY on lines
#   containing one of these excerpts — so editing the matched line, or a new
#   match elsewhere in the file, is no longer covered. Overrides without a
#   matches: list keep the legacy file-wide behavior.
# ---------------------------------------------------------------------------
parse_override_matches() {
  local file="$1"
  local in_fm=0
  local in_override=0
  local in_matches=0
  local lineno=0

  while IFS= read -r line || [[ -n "$line" ]]; do
    ((lineno++)) || true
    if [[ $in_fm -eq 0 && $lineno -eq 1 && "$line" == "---" ]]; then
      in_fm=1; continue
    fi
    if [[ $in_fm -eq 1 && "$line" == "---" ]]; then
      break
    fi
    [[ $in_fm -eq 0 ]] && continue

    if [[ $in_override -eq 0 && "$line" == "sentinel_override:"* ]]; then
      in_override=1; continue
    fi
    [[ $in_override -eq 0 ]] && continue

    if [[ "$line" =~ ^[^[:space:]] ]]; then
      break
    fi

    local stripped="${line#"${line%%[![:space:]]*}"}"  # ltrim

    if [[ "$stripped" == "matches:"* ]]; then
      in_matches=1
      local mrest="${stripped#matches:}"
      mrest="${mrest#"${mrest%%[![:space:]]*}"}"
      # Inline array: matches: ["a", "b"]
      if [[ "$mrest" == "["*"]" ]]; then
        mrest="${mrest#[}"; mrest="${mrest%]}"
        IFS=',' read -ra mitems <<< "$mrest"
        for mitem in "${mitems[@]}"; do
          mitem="${mitem#"${mitem%%[![:space:]]*}"}"; mitem="${mitem%"${mitem##*[![:space:]]}"}"
          mitem="${mitem#\"}"; mitem="${mitem%\"}"; mitem="${mitem#\'}"; mitem="${mitem%\'}"
          [[ -n "$mitem" ]] && printf '%s\n' "$mitem"
        done
        in_matches=0
      fi
      continue
    fi

    if [[ $in_matches -eq 1 ]]; then
      if [[ "$stripped" == "- "* ]]; then
        local val="${stripped#- }"
        val="${val#"${val%%[![:space:]]*}"}"; val="${val%"${val##*[![:space:]]}"}"
        val="${val#\"}"; val="${val%\"}"; val="${val#\'}"; val="${val%\'}"
        [[ -n "$val" ]] && printf '%s\n' "$val"
      else
        in_matches=0
      fi
    fi
  done < "$file"
}

# ---------------------------------------------------------------------------
# scan_file FILE
#   Appends match records to global MATCHES array.
#   Format: "FILE\tPATTERN\tLINE_NO\tEXCERPT"
#   Returns 2 if file not found.
# ---------------------------------------------------------------------------
# _covered PATTERN LINE — 0 when this match is covered by the file's override.
#   classification.* findings are never coverable (Sentinel is non-negotiable).
#   Overrides carrying a matches: list are excerpt-bound: they cover a pattern
#   only on a line containing a recorded excerpt, so re-editing the matched
#   line (or a new match of the same pattern elsewhere) blocks again. Overrides
#   without matches: keep the legacy file-wide behavior.
_covered() {
  local pat="$1" line="$2" ov m
  case "$pat" in classification.*) return 1 ;; esac
  local named=1
  for ov in "${OV_PATTERNS[@]+"${OV_PATTERNS[@]}"}"; do
    [[ "$ov" == "$pat" ]] && named=0 && break
  done
  [[ $named -eq 0 ]] || return 1
  [[ ${#OV_MATCHES[@]} -eq 0 ]] && return 0
  local trimmed="${line#"${line%%[![:space:]]*}"}"
  for m in "${OV_MATCHES[@]}"; do
    # The hook reports long lines truncated to 77 chars + "..." — agents record
    # that excerpt verbatim, so strip the ellipsis before the substring compare
    # or a long-line override could never match its own line.
    m="${m%...}"
    [[ -n "$m" && "$trimmed" == *"$m"* ]] && return 0
  done
  return 1
}

# _scan_line FILE ABS_LINE CONTENT — run every pattern against one line.
_scan_line() {
  local file="$1" abs_line="$2" line="$3"
  local i
  for ((i=0; i<PATTERN_COUNT; i++)); do
    local grep_flags="-E"
    [[ "${PATTERN_ICASE[$i]}" -eq 1 ]] && grep_flags="-iE"

    if printf '%s\n' "$line" | grep -q $grep_flags -- "${PATTERN_REGEXES[$i]}" 2>/dev/null; then
      _covered "${PATTERN_NAMES[$i]}" "$line" && continue
      local excerpt="${line#"${line%%[![:space:]]*}"}"
      [[ ${#excerpt} -gt 80 ]] && excerpt="${excerpt:0:77}..."
      MATCHES+=("$(printf '%s\t%s\t%d\t%s' "$file" "${PATTERN_NAMES[$i]}" "$abs_line" "$excerpt")")
    fi
  done
}

# _classification_check FILE ABS_LINE CONTENT — banner-shaped markers only.
#   Case-sensitive: banners are uppercase by convention, and case-insensitive
#   matching would flag prose ("circuit" contains "cui"). A banner is a line
#   that IS the marker (optionally //CAVEATED), or the long-form phrase
#   anywhere in a line. Filename-embedded markers like "(CUI) document.docx"
#   are deliberately NOT blocked here: path-only references are the sanctioned
#   way to point at classified material (security-policy.md § Session Agent
#   Behavior); Parliament judges those in context at Layer 3. Frontmatter/
#   banner MISMATCH checks are also Layer 3's — this layer only enforces the
#   two unambiguous cases (marker in a no-marker Hive; unmarked marker in a
#   marking-required Hive; anything above CUI anywhere).
_classification_check() {
  local file="$1" abs_line="$2" line="$3"
  local excerpt="${line#"${line%%[![:space:]]*}"}"
  [[ ${#excerpt} -gt 80 ]] && excerpt="${excerpt:0:77}..."

  # Above any Hive's ceiling — always blocked, never overridable.
  if printf '%s\n' "$line" | grep -qE -- '^[[:space:]]*(TOP SECRET|SECRET)([[:space:]]*$|//)'; then
    MATCHES+=("$(printf '%s\t%s\t%d\t%s' "$file" "classification.above-ceiling" "$abs_line" "$excerpt")")
    return
  fi

  if printf '%s\n' "$line" | grep -qE -- '^[[:space:]]*(CUI|FOUO)([[:space:]]*$|//)|CONTROLLED UNCLASSIFIED INFORMATION|UNCLASSIFIED//FOR OFFICIAL USE ONLY'; then
    case "$CLASS_MAX_LEVEL" in
      CUI|FOUO)
        if [[ ${HAS_CLASSIFICATION_FM:-0} -eq 0 ]]; then
          MATCHES+=("$(printf '%s\t%s\t%d\t%s' "$file" "classification.unmarked" "$abs_line" "$excerpt")")
        fi
        ;;
      *)
        MATCHES+=("$(printf '%s\t%s\t%d\t%s' "$file" "classification.marker" "$abs_line" "$excerpt")")
        ;;
    esac
  fi
}

scan_file() {
  local file="$1"
  if [[ ! -f "$file" ]]; then
    printf 'sentinel-pre-push: %s not found\n' "$file" >&2
    return 2
  fi

  OV_PATTERNS=()
  while IFS= read -r p || [[ -n "$p" ]]; do
    [[ -n "$p" ]] && OV_PATTERNS+=("$p")
  done < <(parse_override "$file")

  OV_MATCHES=()
  while IFS= read -r p || [[ -n "$p" ]]; do
    [[ -n "$p" ]] && OV_MATCHES+=("$p")
  done < <(parse_override_matches "$file")

  split_frontmatter "$file"

  # Frontmatter lines (sentinel_override block already excluded).
  local rec
  for rec in "${FM_SCAN_LINES[@]+"${FM_SCAN_LINES[@]}"}"; do
    _scan_line "$file" "${rec%%$'\t'*}" "${rec#*$'\t'}"
  done

  # Body lines: pattern scan + classification-banner scan.
  local idx=0
  for line in "${BODY_LINES[@]+"${BODY_LINES[@]}"}"; do
    ((idx++)) || true
    local abs_line=$(( BODY_START_LINE + idx - 1 ))
    _scan_line "$file" "$abs_line" "$line"
    _classification_check "$file" "$abs_line" "$line"
  done
}

# ---------------------------------------------------------------------------
# report — prints block message to stderr
# ---------------------------------------------------------------------------
report() {
  [[ ${#MATCHES[@]} -eq 0 ]] && return

  local -a seen_files=()
  for m in "${MATCHES[@]}"; do
    local f="${m%%	*}"
    local found=0
    for sf in "${seen_files[@]+"${seen_files[@]}"}"; do
      [[ "$sf" == "$f" ]] && found=1 && break
    done
    [[ $found -eq 0 ]] && seen_files+=("$f")
  done

  printf 'Pre-push Sentinel block: %d sensitive-data match(es) in %d file(s):\n' \
    "${#MATCHES[@]}" "${#seen_files[@]}" >&2

  for f in "${seen_files[@]}"; do
    printf '  %s\n' "$f" >&2
    for m in "${MATCHES[@]}"; do
      IFS=$'\t' read -r mfile mpat mline mexcerpt <<< "$m"
      [[ "$mfile" == "$f" ]] && printf '    line %s [%s]: %s\n' "$mline" "$mpat" "$mexcerpt" >&2
    done
  done

  printf '\n' >&2
  cat >&2 <<'BLOCKMSG'
Push blocked. The agent must diagnose each match: redact real sensitive
content in place (the common case), or — only if the regex is genuinely
wrong — get explicit user confirmation and record a `sentinel_override`
in the file's frontmatter. classification.* findings cannot be overridden:
remove the marker or re-home the content per protocol/security-policy.md
§ Classification Discipline. See protocol/sensitive-data-patterns.md and
references/pre-push-sentinel.md.
BLOCKMSG
}

# ---------------------------------------------------------------------------
# run_gate_extensions FILE...
#   Runs each Hive-declared gate extension after the built-in pattern scan has
#   already passed. Returns 0 if every gate allows the push, 1 otherwise.
#
#   Contract for a gate command:
#     - receives the candidate files as "$@" (same list the pattern scan saw)
#     - receives HIVE_ROOT and APIARY_SENTINEL_PASSED=1 in the environment
#     - exit 0 = allow, non-zero = block
#     - anything it writes to stdout/stderr is shown to the contributor
#
#   Extensions cannot reach this function unless the built-in scan passed, so
#   they can only ever ADD a block — never remove one.
#
#   Gates run sequentially in filename order, with no early exit — every gate
#   runs even after one has already blocked, so the contributor sees all
#   failures in one push. Worst-case added latency is therefore the SUM of the
#   gates' timeout_seconds, not the slowest one.
# ---------------------------------------------------------------------------
run_gate_extensions() {
  [[ ${GATE_COUNT:-0} -eq 0 ]] && return 0

  local repo_root; repo_root="$(git rev-parse --show-toplevel 2>/dev/null || printf '.')"
  local gate_status=0

  for ((g=0; g<GATE_COUNT; g++)); do
    # One tab-delimited record per gate; required_tools is last and may be empty.
    local name cmd onerr tmo tools
    IFS=$'\t' read -r name cmd onerr tmo tools <<<"${GATES[$g]}"

    # Missing prerequisite tools produce an actionable message rather than a
    # bare non-zero exit the contributor has to decode.
    local missing=""
    for t in $tools; do
      [[ -z "$t" ]] && continue
      command -v "$t" >/dev/null 2>&1 || missing="$missing $t"
    done
    if [[ -n "$missing" ]]; then
      if [[ "$onerr" == "warn" ]]; then
        printf 'gate [%s]: SKIPPED — missing tool(s):%s (on_error: warn)\n' "$name" "$missing" >&2
        continue
      fi
      printf 'gate [%s]: BLOCKED — missing required tool(s):%s\n' "$name" "$missing" >&2
      printf '  This gate fails closed. Install the tool(s), or set `on_error: warn`\n' >&2
      printf '  in the gate extension if degraded operation is genuinely acceptable.\n' >&2
      gate_status=1
      continue
    fi

    # A declared timeout is only enforceable if `timeout` is installed; without
    # it the gate runs unbounded, which is said out loud rather than assumed.
    local pre=()
    if [[ "$tmo" -gt 0 ]]; then
      if command -v timeout >/dev/null 2>&1; then
        pre=(timeout "$tmo")
      else
        printf 'gate [%s]: timeout_seconds=%s declared but `timeout` is not installed — running unbounded\n' \
          "$name" "$tmo" >&2
      fi
    fi

    local rc=0
    HIVE_ROOT="$repo_root" APIARY_SENTINEL_PASSED=1 \
      "${pre[@]+"${pre[@]}"}" bash -c "$cmd \"\$@\"" _ "$@" || rc=$?
    if [[ $rc -eq 124 && ${#pre[@]} -gt 0 ]]; then
      printf 'gate [%s]: timed out after %ss\n' "$name" "$tmo" >&2
    fi

    if [[ $rc -ne 0 ]]; then
      if [[ "$onerr" == "warn" ]]; then
        printf 'gate [%s]: non-zero exit (%d) — allowed, on_error: warn\n' "$name" "$rc" >&2
      else
        printf 'gate [%s]: BLOCKED (exit %d)\n' "$name" "$rc" >&2
        gate_status=1
      fi
    fi
  done

  return $gate_status
}

# ---------------------------------------------------------------------------
# sentinel_base LOCAL_SHA REMOTE_SHA — the commit to diff against.
#
#   The remote sha is authoritative when the branch already exists upstream.
#   When it does not (a zero sha — every first push of a new branch), we have to
#   work out what "new" means, and the answer matters more than it looks:
#
#   This used to fall back to `git hash-object -t tree /dev/null` — the EMPTY
#   TREE — so the diff became the entire repository. Every contribution starts on
#   a fresh branch, so in practice every contribution was reported as changing
#   every `_inbox/` and `sources/` file in the Hive. For the pattern scan that is
#   merely wasteful. For gate extensions it is wrong: a gate receives the file
#   list as its argument set and reasonably reads it as "this contribution", so a
#   gate asserting a per-contribution property (an attestation, a sign-off) would
#   demand it for every pending entry in the repo, including other people's.
#   A check that asks for that gets routed around with --no-verify, which skips
#   every layer.
#
#   Resolution order, each falling through on failure:
#     1. the branch's own upstream, if it has one
#     2. origin/<default_branch>, then <default_branch> — baked in from hive.yml
#     3. origin/HEAD, for a hook generated without a HIVE_ROOT
#     4. the empty tree, and say so on stderr
#
#   A candidate is only usable if its merge base is not the local tip itself. If
#   it is, the candidate already contains everything being pushed and yields an
#   empty diff — which is precisely the case when the branch being pushed IS the
#   default branch and the remote does not have it yet. There, nothing is "new
#   relative to" anything and the whole tree genuinely is the contribution, so
#   the empty tree is the right answer rather than a fallback.
#
#   Step 4 stays as a last resort because over-reporting is the safe direction
#   for the pattern scan — but it is now loud rather than silent, because a gate
#   behaving oddly on a first push is otherwise very hard to explain.
# ---------------------------------------------------------------------------
sentinel_base() {
  local local_sha="$1" remote_sha="$2"
  local zero="0000000000000000000000000000000000000000"
  local base ref

  if [[ "$remote_sha" != "$zero" && -n "$remote_sha" ]]; then
    printf '%s\n' "$remote_sha"; return 0
  fi

  # Candidates in preference order. An empty entry is skipped.
  for ref in "HEAD@{upstream}" \
             ${DEFAULT_BRANCH:+"origin/$DEFAULT_BRANCH" "$DEFAULT_BRANCH"} \
             "$(git symbolic-ref --quiet --short refs/remotes/origin/HEAD 2>/dev/null)"; do
    [[ -n "$ref" ]] || continue
    git rev-parse --verify --quiet "$ref" >/dev/null 2>&1 || continue
    base=$(git merge-base "$local_sha" "$ref" 2>/dev/null) || continue
    [[ -n "$base" ]] || continue
    # The candidate already contains the tip: no useful base here.
    [[ "$base" == "$local_sha" ]] && continue
    printf '%s\n' "$base"; return 0
  done

  printf 'sentinel-pre-push: no upstream and no default branch to compare against;\n' >&2
  printf '  reviewing the full tree. Gates that assert a per-contribution property\n' >&2
  printf '  will see every candidate file, not just this contribution.\n' >&2
  git hash-object -t tree /dev/null 2>/dev/null
}

# ---------------------------------------------------------------------------
# list_sentinel_changes — reads git pre-push stdin, outputs changed
#   _inbox/*.md and sources/**/*.{md,txt} files
# ---------------------------------------------------------------------------
list_sentinel_changes() {
  local zero="0000000000000000000000000000000000000000"
  while IFS= read -r stdin_line || [[ -n "$stdin_line" ]]; do
    [[ -z "$stdin_line" ]] && continue
    read -r _lref local_sha _rref remote_sha <<< "$stdin_line"
    [[ "$local_sha" == "$zero" ]] && continue

    local base
    base=$(sentinel_base "$local_sha" "$remote_sha")

    git diff --name-only "$base" "$local_sha" -- "_inbox/" "sources/" 2>/dev/null | \
      grep -E '^(_inbox/[^/]+\.md|sources/.+\.(md|txt))$' || true
  done | sort -u | while IFS= read -r f; do
    [[ -f "$f" ]] && printf '%s\n' "$f"
  done
}

# ---------------------------------------------------------------------------
# cmd_hook — git pre-push mode
# ---------------------------------------------------------------------------
#   Gate extensions run HERE ONLY — deliberately not in `scan` / `scan-dir`.
#   Those subcommands are the reusable pattern-scan primitive that Parliament
#   and hardened gates themselves invoke; running gates there would recurse
#   (gate -> its own script -> `scan` -> gate -> ...).
cmd_hook() {
  local -a files=()
  while IFS= read -r f || [[ -n "$f" ]]; do
    [[ -n "$f" ]] && files+=("$f")
  done < <(list_sentinel_changes)

  for f in "${files[@]+"${files[@]}"}"; do
    scan_file "$f" || true
  done

  if [[ ${#MATCHES[@]} -gt 0 ]]; then
    report; exit 1
  fi

  # Built-in Sentinel passed. Hive-declared gates may still block.
  run_gate_extensions "${files[@]+"${files[@]}"}" || exit 1
  exit 0
}

# ---------------------------------------------------------------------------
# cmd_scan FILE... — explicit file scan
# ---------------------------------------------------------------------------
cmd_scan() {
  for f in "$@"; do
    scan_file "$f" || exit 2
  done

  if [[ ${#MATCHES[@]} -gt 0 ]]; then
    report; exit 1
  fi
  exit 0
}

# ---------------------------------------------------------------------------
# cmd_scan_dir DIR — scan DIR/_inbox/*.md plus DIR/sources/**/*.{md,txt},
#   the same surface the pre-push mode covers, so Parliament's catch-all scan
#   sees everything a --no-verify push or manual drop could have landed.
# ---------------------------------------------------------------------------
cmd_scan_dir() {
  local dir="${1:-}"
  if [[ -z "$dir" ]]; then
    printf 'sentinel-pre-push: usage: scan-dir <HIVE_ROOT>\n' >&2; exit 2
  fi
  if [[ ! -d "$dir" ]]; then
    printf 'sentinel-pre-push: %s is not a directory\n' "$dir" >&2; exit 2
  fi
  if [[ ! -d "$dir/_inbox" ]]; then
    printf 'sentinel-pre-push: no _inbox/ under %s\n' "$dir" >&2; exit 2
  fi

  local -a targets=()
  while IFS= read -r f || [[ -n "$f" ]]; do
    [[ -n "$f" ]] && targets+=("$f")
  done < <(find "$dir/_inbox" -maxdepth 1 -name '*.md' ! -name '_*' | sort)
  if [[ -d "$dir/sources" ]]; then
    while IFS= read -r f || [[ -n "$f" ]]; do
      [[ -n "$f" ]] && targets+=("$f")
    done < <(find "$dir/sources" -type f \( -name '*.md' -o -name '*.txt' \) | sort)
  fi

  [[ ${#targets[@]} -eq 0 ]] && exit 0

  for f in "${targets[@]}"; do
    scan_file "$f" || true
  done

  if [[ ${#MATCHES[@]} -gt 0 ]]; then
    report; exit 1
  fi
  exit 0
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
MATCHES=()

case "${1:-}" in
  scan)     shift; cmd_scan "$@" ;;
  scan-dir) shift; cmd_scan_dir "${1:-}" ;;
  *)        cmd_hook ;;
esac
HOOK_BODY
